const dietas = [
  {
    condicao: 'lactose',
    opcao: 'engordar',
    dieta: "O cardápio diário inclui no café da manhã uma fatia de pão integral com manteiga de amendoim ou creme de amêndoas, uma banana amassada com mel ou xarope de bordo, um copo de leite de amêndoas ou leite de coco fortificado com cálcio e vitamina D, além de aveia cozida com água ou leite vegetal e sementes de chia ou linhaça, com ovo mexido (se não for vegano). No lanche da manhã, é consumida uma maçã com castanhas ou nozes e hummus com cenoura ou pepino fatiado. No almoço, a refeição conta com arroz integral ou quinoa, frango grelhado ou carne magra (ou tofu/tempeh para versão vegana), legumes cozidos (como abóbora, brócolis e cenoura), abacate temperado com limão, azeite de oliva e sal, e azeite extra virgem para temperar. O lanche da tarde é uma fatia de pão integral com abacate ou pasta de amendoim, amêndoas ou castanha de caju, e um copo de suco natural de frutas. O jantar inclui uma salada de folhas verdes e tomate, filé de salmão grelhado ou peito de frango, batata-doce assada ou cozida, e feijão (ou lentilhas para veganos). Na ceia, é consumido um copo de leite vegetal enriquecido com cálcio e vitamina D, acompanhado de granola sem lactose ou mix de castanhas e sementes."
  },
  
  {
    condicao: 'lactose',
    opcao: 'emagrecer',
    dieta: "O cardápio diário começa com um café da manhã composto por uma fatia de pão integral com manteiga de amêndoas ou creme de abacate, um ovo cozido ou mexido, uma porção de frutas frescas como maçã ou melancia, e um copo de chá verde ou café preto sem açúcar. No lanche da manhã, são consumidos um punhado de amêndoas ou nozes (cerca de 10 unidades) e opcionalmente, fatias de pepino ou cenoura crua. O almoço inclui uma porção de salada verde com folhas escuras (rúcula, espinafre, alface), temperada com azeite de oliva, vinagre e limão, peito de frango grelhado ou tofu, quinoa ou arroz integral (em pequena quantidade, cerca de 1/2 xícara) e brócolis ou abobrinha no vapor. No lanche da tarde, é servido um iogurte sem lactose (de coco, amêndoas ou soja) com sementes de chia ou linhaça, além de uma fatia de mamão ou melão. O jantar é composto por uma salada de folhas verdes com abacate e tomate, peixe grelhado (como tilápia ou salmão) ou carne magra (frango ou peru), legumes grelhados (berinjela, pimentão, abobrinha) ou legumes cozidos no vapor, e uma fatia de batata-doce assada ou couve-flor. Para a ceia, a opção é gelatina sem açúcar ou frutas vermelhas, acompanhadas de uma xícara de chá de camomila ou hibisco, que ajudam na digestão e no relaxamento."
  },

  {
    condicao: 'amendoa',
    opcao: 'engordar',
    dieta: "O cardápio diário começa com o café da manhã, composto por uma fatia de pão integral com 2 colheres de sopa de manteiga de cacau (ou manteiga de girassol, para uma versão mais leve), uma banana com mel ou xarope de bordo, um copo de leite de coco ou leite de aveia (fortificados com cálcio e vitamina D), uma porção de aveia com leite vegetal, sementes de chia ou linhaça e canela, e um ovo mexido (ou tofu mexido como alternativa vegana). No lanche da manhã, consome-se uma maçã ou pêra com 2 colheres de sopa de castanhas de caju ou nozes, além de uma fatia de pão integral com creme de abacate temperado com limão e azeite de oliva. No almoço, a refeição inclui arroz integral ou quinoa, frango grelhado ou carne magra (ou tempeh/tofu para veganos), brócolis ou espinafre cozidos, abacate temperado com azeite de oliva e limão, e uma colher de sopa de azeite de oliva para temperar a salada ou legumes. O lanche da tarde conta com hummus acompanhado de palitos de cenoura, pepino ou salsão, uma porção de frutas secas (como damasco ou tâmaras), e uma fatia de pão integral com pasta de girassol ou pasta de caju. No jantar, há peixe grelhado (como salmão ou tilápia) ou carne de peru assada, batata-doce assada ou cozida, uma salada com folhas verdes (rúcula, alface, tomate, pepino), e uma colher de sopa de azeite de oliva ou óleo de abacate para temperar. Para a ceia, a opção é um copo de leite de coco ou leite de aveia, um punhado de castanhas de caju ou nozes, e uma fatia de pão integral com pasta de girassol ou outra pasta de oleaginosa, exceto de amêndoas."
  },

  {
    condicao: 'amendoa',
    opcao: 'emagrecer',
    dieta: "O cardápio diário começa com o café da manhã, composto por uma fatia de pão integral com pasta de abacate temperada com limão e sal, um ovo cozido ou mexido (ou tofu mexido para versão vegana), uma porção de frutas frescas como maçã ou melancia, e uma xícara de chá verde ou café preto sem açúcar. No lanche da manhã, é consumida uma porção de frutas vermelhas (morango, mirtilo, framboesa) com sementes de chia, além de uma fatia de pepino ou cenoura crua, podendo ser acompanhada de hummus. No almoço, há uma salada verde com folhas escuras (rúcula, espinafre, alface) e tomate, temperada com azeite de oliva e vinagre balsâmico, filé de frango grelhado ou peixe grelhado (como tilápia, sardinha ou salmão), quinoa ou arroz integral (cerca de 1/2 xícara), e legumes cozidos ou grelhados (brócolis, couve-flor, abobrinha, cenoura). O lanche da tarde inclui iogurte sem lactose (de soja, coco ou aveia) com sementes de linhaça ou chia, uma porção de cenoura crua ou maçã, e um punhado de castanhas de caju ou nozes (cerca de 10 unidades). O jantar é composto por uma salada de folhas verdes (alface, rúcula, espinafre) com pepino, tomate e cenoura ralada, peixe assado (tilápia, salmão ou truta) ou tofu grelhado, batata-doce assada ou cozida (tamanho médio), e legumes no vapor (como couve-flor, abobrinha e cenoura). Para a ceia, a opção é uma xícara de chá de camomila ou chá de hibisco, acompanhada de gelatina sem açúcar ou uma pequena porção de frutas frescas."
  },

  {
    condicao: 'diabetes',
    opcao: 'engordar',
    dieta: "A dieta proposta para emagrecimento, especialmente para pessoas com diabetes, foca na redução da ingestão calórica e no controle dos níveis de glicose no sangue, mantendo uma alimentação balanceada. O café da manhã inclui 2 fatias de pão integral ou de centeio (preferencialmente sem açúcar), um ovo cozido ou omelete com 2 claras e 1 gema, acompanhado de legumes como espinafre ou cogumelos, uma fatia de abacate (rico em gorduras saudáveis e fibras), um copo de leite desnatado ou leite de amêndoas (sem açúcar), e uma xícara de café preto sem açúcar ou chá verde. No lanche da manhã, a opção é uma maçã ou pêra (frutas com baixo índice glicêmico), um punhado de castanhas de caju ou nozes (ricas em gorduras boas), e uma fatia de queijo branco ou queijo cottage (sem lactose, se necessário). O almoço inclui filé de frango grelhado ou carne magra (como patinho ou músculo), batata-doce assada ou cozida (carboidrato de baixo índice glicêmico), uma salada de folhas verdes com azeite de oliva, limão e vinagre, feijão ou lentilhas (ricas em fibras e proteínas), e brócolis ou abóbora cozida. No lanche da tarde, pode-se consumir uma fatia de pão integral com pasta de abacate ou pasta de girassol, uma fatia de tomate ou pepino, e um copo de suco verde (feito com couve, pepino, gengibre e limão, sem adição de açúcar). O jantar é composto por peixe grelhado (como salmão ou tilápia), arroz integral ou quinoa (cerca de ½ xícara), legumes cozidos no vapor (cenoura, couve-flor, abobrinha), e abacate ou castanha-do-pará (para adicionar calorias e gorduras boas). Para a ceia, a opção é um copo de leite desnatado ou leite vegetal (como leite de coco ou aveia), um punhado de castanhas de caju ou amêndoas, e uma fatia de queijo cottage ou queijo branco."
  },

  {
    condicao: 'diabetes',
    opcao: 'emagrecer',
    dieta: "A dieta proposta é focada em alimentos saudáveis e de baixo índice glicêmico, com ênfase no controle de calorias e manutenção de um equilíbrio nutricional ideal para quem busca emagrecimento. O café da manhã inclui uma fatia de pão integral ou de centeio (preferencialmente sem açúcar), um ovo cozido ou omelete de claras (2 claras e 1 gema) com espinafre, tomate e cogumelos, uma fatia de abacate (em pequena quantidade, pois é calórico, mas saudável), uma xícara de café preto sem açúcar ou chá verde, e um copo de leite desnatado ou leite de amêndoas sem açúcar. No lanche da manhã, consome-se uma maçã ou kiwi (frutas com baixo índice glicêmico), um punhado de amêndoas ou nozes, e uma fatia de pepino ou cenoura crua. O almoço inclui filé de frango grelhado ou peixe (como tilápia, salmão ou sardinha), uma salada verde com folhas escuras (rúcula, alface, espinafre, tomate), abóbora assada ou berinjela grelhada (legumes com baixo índice glicêmico), feijão ou lentilhas (evitando carboidratos simples como arroz branco), e uma colher de sopa de azeite de oliva extra virgem para temperar. O lanche da tarde é composto por iogurte grego natural (sem açúcar) com sementes de chia ou linhaça, uma fatia de tomate ou pepino, e um punhado de castanhas de caju ou nozes (em pequena quantidade). No jantar, é servido carne magra (como frango ou peixe), uma salada de folhas verdes com abacate, pepino e tomate, brócolis cozido ou couve-flor, e abóbora assada ou aspargos grelhados. Para a ceia, a opção é um copo de leite desnatado ou leite de coco (sem açúcar), um punhado de nozes ou castanhas (em pequena quantidade), e uma fatia de queijo branco ou queijo cottage (sem lactose, se necessário). A dieta é balanceada, priorizando alimentos nutritivos e de baixo índice glicêmico para ajudar na redução de peso e controle glicêmico."
  },

  {
    condicao: 'mar',
    opcao: 'engordar',
    dieta: "O cardápio proposto segue uma alimentação balanceada e saudável, com foco em alimentos nutritivos e de baixo índice glicêmico. O café da manhã inclui uma fatia de pão integral com 2 colheres de sopa de pasta de amendoim (sem adição de açúcar) ou pasta de girassol, uma banana amassada com mel ou xarope de bordo, um copo de leite de amêndoas ou leite de aveia (fortificado com cálcio e vitamina D), dois ovos mexidos ou omelete com cogumelos, espinafre e tomate, e uma porção de aveia cozida com leite vegetal, chia e canela. No lanche da manhã, são consumidos uma maçã ou pêra (frutas com baixo índice glicêmico), um punhado de castanhas de caju ou nozes (ricas em gorduras boas e calorias), e um iogurte sem lactose (ou iogurte de soja) com sementes de chia. O almoço inclui arroz integral ou quinoa, frango grelhado ou carne magra (como peito de frango ou carne de peru), batata-doce assada ou cozida, uma salada de folhas verdes (rúcula, alface, espinafre) com azeite de oliva, limão e vinagre, e uma porção de brócolis ou abóbora assada. O lanche da tarde consiste em uma fatia de pão integral com 2 colheres de sopa de pasta de abacate ou pasta de girassol, um punhado de amêndoas ou castanha-do-pará, e um copo de suco de laranja natural (sem açúcar). O jantar é composto por peito de frango grelhado ou tofu (para versão vegana), arroz integral ou quinoa, uma salada de legumes (cenoura, pepino, tomate, abobrinha), abacate temperado com azeite de oliva e limão, e uma colher de sopa de azeite de oliva extra virgem para temperar a salada ou legumes. Na ceia, a opção é um copo de leite vegetal (coco ou aveia), um punhado de castanhas de caju ou amêndoas, e uma fatia de queijo cottage ou queijo branco (se for tolerante à lactose). Este plano alimentar é equilibrado, com proteínas magras, gorduras saudáveis, carboidratos complexos e muitas fibras, promovendo saúde e bem-estar."
  },

  {
    condicao: 'mar',
    opcao: 'emagrecer',
    dieta: "O cardápio proposto segue uma alimentação balanceada e saudável, com foco em alimentos nutritivos e de baixo índice glicêmico. O café da manhã inclui uma fatia de pão integral com 2 colheres de sopa de pasta de amendoim (sem adição de açúcar) ou pasta de girassol, uma banana amassada com mel ou xarope de bordo, um copo de leite de amêndoas ou leite de aveia (fortificado com cálcio e vitamina D), dois ovos mexidos ou omelete com cogumelos, espinafre e tomate, e uma porção de aveia cozida com leite vegetal, chia e canela. No lanche da manhã, são consumidos uma maçã ou pêra (frutas com baixo índice glicêmico), um punhado de castanhas de caju ou nozes (ricas em gorduras boas e calorias), e um iogurte sem lactose (ou iogurte de soja) com sementes de chia. O almoço inclui arroz integral ou quinoa, frango grelhado ou carne magra (como peito de frango ou carne de peru), batata-doce assada ou cozida, uma salada de folhas verdes (rúcula, alface, espinafre) com azeite de oliva, limão e vinagre, e uma porção de brócolis ou abóbora assada. O lanche da tarde consiste em uma fatia de pão integral com 2 colheres de sopa de pasta de abacate ou pasta de girassol, um punhado de amêndoas ou castanha-do-pará, e um copo de suco de laranja natural (sem açúcar). O jantar é composto por peito de frango grelhado ou tofu (para versão vegana), arroz integral ou quinoa, uma salada de legumes (cenoura, pepino, tomate, abobrinha), abacate temperado com azeite de oliva e limão, e uma colher de sopa de azeite de oliva extra virgem para temperar a salada ou legumes. Na ceia, a opção é um copo de leite vegetal (coco ou aveia), um punhado de castanhas de caju ou amêndoas, e uma fatia de queijo cottage ou queijo branco (se for tolerante à lactose). Este plano alimentar é equilibrado, com proteínas magras, gorduras saudáveis, carboidratos complexos e muitas fibras, promovendo saúde e bem-estar."
  },

  {
    condicao: `nenhuma`,
    opcao: `engordar`,
    dieta: `Esta dieta é ideal para quem busca um ganho de peso saudável, com foco no aumento de massa muscular e no fornecimento de nutrientes essenciais de forma equilibrada e nutritiva. O café da manhã é composto por pão integral com pasta de amendoim ou creme de amêndoas, banana com mel ou xarope de bordo, leite integral ou de coco, ovos mexidos ou omelete com queijo e espinafre, além de aveia cozida com leite integral, chia e canela, oferecendo uma boa dose de proteínas, gorduras boas e carboidratos complexos. O lanche da manhã inclui frutas como maçã ou pêra, castanhas e iogurte grego integral com mel e granola, promovendo saciedade e nutrição. O almoço é composto por arroz integral ou quinoa, frango grelhado ou peixe, batata-doce ou mandioca assada, salada verde com azeite de oliva, abacate e limão, e legumes cozidos ou grelhados, proporcionando uma refeição equilibrada com proteínas, carboidratos de baixo índice glicêmico e gorduras saudáveis. O lanche da tarde traz um sanduíche de pão integral com pasta de abacate e queijo, amêndoas ou castanha-do-pará, além de suco natural ou smoothie, garantindo energia e nutrientes extras. O jantar é uma refeição leve, com carne magra ou tofu grelhado, arroz integral ou quinoa, legumes cozidos ou assados e abacate ou guacamole, favorecendo a recuperação muscular. Para a ceia, o leite integral ou leite de coco com castanhas e queijo cottage ou branco fornece cálcio e proteínas, finalizando o dia com nutrientes para regeneração muscular. Com refeições ricas em proteínas, gorduras saudáveis e carboidratos complexos, essa dieta é ideal para quem deseja ganhar peso de forma saudável, mantendo o equilíbrio nutricional e promovendo o aumento de massa muscular.`
  },

  {
    condicao: `nenhuma`,
    opcao: `emagrecer`,
    dieta: `Essa dieta é voltada para quem busca uma alimentação equilibrada e saudável, com foco em controle de peso e manutenção de uma alimentação com baixo índice glicêmico. O café da manhã é composto por uma fatia de pão integral ou de centeio, combinada com um ovo cozido ou omelete de claras (2 claras e 1 gema) com espinafre, tomate e cogumelos, além de uma fatia de abacate (em pequena quantidade), chá verde ou café preto sem açúcar, e leite desnatado ou leite de amêndoas sem açúcar, fornecendo proteínas, gorduras saudáveis e fibras. O lanche da manhã inclui frutas com baixo índice glicêmico, como maçã ou kiwi, amêndoas ou nozes (em pequenas quantidades) e pepino ou cenoura crua, proporcionando saciedade e nutrientes. O almoço é equilibrado, com filé de frango grelhado, peixe (como tilápia ou salmão) ou tofu grelhado, arroz integral ou quinoa (1/2 xícara), salada de folhas verdes temperada com azeite de oliva, limão e vinagre, e legumes cozidos no vapor, como abóbora, brócolis e couve-flor, garantindo uma refeição rica em proteínas, fibras e antioxidantes. O lanche da tarde inclui uma fatia de pão integral com pasta de abacate ou pasta de girassol, amêndoas ou castanha-do-pará, e um copo de suco verde feito com couve, pepino, gengibre e limão, sem adição de açúcar, fornecendo energia e nutrientes adicionais. O jantar consiste em uma porção de carne magra (como peito de frango ou peixe) ou tofu grelhado, acompanhada de uma salada de folhas verdes com pepino, tomate e cenoura ralada, brócolis ou abóbora cozida, e uma pequena porção de abacate ou guacamole, além de azeite de oliva para temperar. Para a ceia, um copo de leite desnatado ou leite vegetal (como coco ou aveia) com nozes ou castanhas e uma fatia de queijo cottage ou queijo branco (se tolerante à lactose) ajuda a finalizar o dia com um toque de proteína e cálcio. Essa dieta proporciona um bom equilíbrio entre macronutrientes, com foco em proteínas magras, carboidratos complexos e gorduras saudáveis, ideal para quem deseja manter o peso ou seguir um estilo de vida saudável com controle glicêmico.`


  },
  {
    condicao: `diabetes`,
    opcao: `manter`,
    dieta: `Esta dieta é ideal para pessoas com diabetes, focando em alimentos de baixo índice glicêmico para manter o equilíbrio de açúcar no sangue e garantir uma alimentação saudável. No café da manhã, inclua pão integral com pasta de abacate, ovos mexidos com espinafre e uma fruta como maçã ou pera. O lanche da manhã pode ser iogurte grego natural sem açúcar com granola sem adição de açúcar e castanhas. O almoço pode ser composto por arroz integral ou quinoa, frango grelhado ou peixe, batata-doce assada e uma salada verde com azeite de oliva e limão. No lanche da tarde, faça um sanduíche de pão integral com queijo branco e pasta de abacate, acompanhado de uma porção de nozes ou castanhas. O jantar pode ser carne magra ou tofu grelhado com legumes cozidos ou assados e abacate. Finalize o dia com uma ceia leve, como leite de amêndoas sem açúcar com castanhas ou queijo cottage. Essa dieta ajuda a manter os níveis de glicose estáveis enquanto oferece uma alimentação rica em nutrientes.`,
  },
  {
    condicao: `amendoa`,
    opcao: `manter`,
    dieta: `Esta dieta é ideal para pessoas com intolerância a amêndoas, oferecendo alternativas nutritivas para manter o peso de forma equilibrada. No café da manhã, opte por pão integral com pasta de abacate ou creme de amendoim, ovos mexidos com espinafre e uma fruta como banana ou maçã. No lanche da manhã, escolha iogurte natural com granola sem amêndoas e castanhas de caju ou nozes. O almoço pode ser composto por arroz integral, frango grelhado ou peixe, batata-doce ou mandioca assada e salada verde com azeite de oliva. No lanche da tarde, faça um sanduíche de pão integral com queijo branco e pasta de abacate, acompanhado de nozes ou castanha-do-pará. O jantar pode incluir carne magra ou tofu grelhado, legumes assados e abacate. Finalize o dia com uma ceia leve, como leite de coco com castanhas ou queijo cottage, para garantir a ingestão de nutrientes essenciais.`,
  },
  {
    condicao: `lactose`,
    opcao: `manter`,
    dieta: `Esta dieta é ideal para pessoas que buscam manter o peso de forma saudável, com foco em alternativas para quem tem intolerância à lactose. No café da manhã, inclua pão integral com pasta de abacate ou creme de amendoim, ovos mexidos com espinafre e uma fruta como banana ou maçã. Para o lanche da manhã, opte por iogurte de coco ou amêndoas com granola sem lactose e castanhas. O almoço pode ser composto por arroz integral, frango grelhado ou peixe, batata-doce ou mandioca assada, e uma salada verde com azeite de oliva. No lanche da tarde, faça um sanduíche com pão integral, pasta de abacate, queijo sem lactose e uma porção de amêndoas. O jantar pode ser carne magra ou tofu grelhado com legumes assados e abacate. Finalize com uma ceia leve, como leite de amêndoas ou leite de coco com castanhas, para garantir a ingestão de gorduras saudáveis e proteínas.`,
  },
  {
    condicao: `nenhuma`,
    opcao: `manter`,
    dieta: `Esta dieta é ideal para quem busca manter o peso de forma saudável, com refeições equilibradas e nutritivas. O café da manhã pode incluir pão integral com pasta de abacate ou creme de amendoim, ovos mexidos com espinafre, uma fruta como banana ou maçã e aveia cozida com leite ou leite vegetal. No lanche da manhã, uma porção de iogurte natural com granola e castanhas promove saciedade. O almoço pode ser composto por arroz integral ou quinoa, frango grelhado ou peixe, batata-doce ou mandioca assada, e uma salada verde com azeite e limão. O lanche da tarde pode incluir um sanduíche de pão integral com queijo branco e abacate, acompanhado de amêndoas ou castanha-do-pará e um suco natural. Para o jantar, opte por carne magra ou tofu grelhado com legumes assados e uma porção de abacate. Finalize o dia com uma ceia leve, como leite de coco com castanhas ou queijo cottage, oferecendo proteínas e gorduras saudáveis para a regeneração muscular.`,
  },
  {
    condicao: `mar`,
    opcao: `manter`,
    dieta: "Esta dieta é ideal para pessoas com intolerância a frutos do mar, mantendo o equilíbrio nutricional com fontes alternativas de proteínas e nutrientes. No café da manhã, inclua pão integral com pasta de abacate, ovos mexidos com espinafre e uma fruta como banana ou maçã. Para o lanche da manhã, aposte em iogurte natural com granola e castanhas. O almoço pode ser composto por arroz integral, frango grelhado ou carne bovina magra, batata-doce ou mandioca assada, e uma salada verde com azeite de oliva. No lanche da tarde, faça um sanduíche de pão integral com queijo e pasta de abacate, acompanhado de castanhas ou nozes. Para o jantar, opte por uma proteína magra como peito de frango ou tofu grelhado, com legumes assados e batata-doce. Finalize com uma ceia leve, como leite de coco com castanhas ou queijo cottage, para garantir nutrientes essenciais durante a noite."
  },
]

export default dietas